version: '3'

services:
  app_im:
    build: ./
    env_file:
      - ./config/.env
    command: ./app
    ports:
      - "8080:8080"

  app_db:
    build: .
    command: ./wait-for-postgres.sh db ./app -db
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
      DB_PASSWORD: "postgres"
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql