version: '3'

services:
  app_db:
    build:
      context: .
    env_file:
      - ./config/.env
    command: ./app -db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/